### ISSUE TITLE
About paper Figure 4

### ISSUE THREAD

**Issue by ckx506772099** [VDIGPKU/T-SEA#1]
Hello, I read in the paper that a small patch scale is better, and it is also the same in the figure. But why is the description "A large patch scale during training will cause the test mAP to drop lower and faster"

**Comment by celinechanny** [comment]
Hi, thanks for your interest in our work.
I'm afraid that it was a typo made in the title of Figure 4.
The actual description would be that a **small** patch scale is favorable such that _"A small patch scale during training will cause the test mAP to drop lower and faster."_

**Comment by celinechanny** [comment]
Many thanks for bringing that to our attention. You are welcome to reopen this issue if you have any other questions.
