### ISSUE TITLE
INRIA Person's generated label in google drive 

### ISSUE THREAD

**Issue by ChnanChan** [VDIGPKU/T-SEA#10]
Hi, thanks for your interesting research. I want to evaluate your code on INRIA person dataset, but when I click generated label of INRIA, it goes to COCO labels. How can I get INRIA labels (e.g. faster_rcnn_rescale or yolov5-rescale-labels)?

**Comment by zycXD** [comment]
Faster RCNN and YoloV5 detectors are supported by our repo, and we've provided the generated labels in the cloud. Please see the README file carefully.

If you want to generate the labels by yourself, please check the script [gen_det_labels.py](https://github.com/VDIGPKU/T-SEA/blob/main/utils/preprocesser/gen_det_labels.py) and [README](https://github.com/VDIGPKU/T-SEA/blob/main/utils/preprocesser/README.md) to generate label files in a correct format. Duplicate with Issue #6.
