### ISSUE TITLE
About paper Figure 5

### ISSUE THREAD

**Issue by ioo0s** [VDIGPKU/T-SEA#11]
When I tried to reproduce the situation in Figure 5, I found that I could not get similar results.
patch use: `ssd-combine-scale-1.png`
yolov5 run cmd:   `python detect.py --source 0 --iou-thres 0.45 --classes 0` (default use yolov5s.pt)

I would like to ask, is the reason for not getting similar results because specific images need to be added to the training set?

**Comment by zycXD** [comment]
We use the original INRIA training set, with no additional data added. There may be a difference between digital and physical evaluation cases. We use the metric AP as the digital evaluation following the previous works, which still shows if mistakes are made by the detectors. However, it may be a limitation that the performance evaluated based on attack success rate(more consistent to the human eye) can be inconsistent. So we recommend reproducing the AP results if you evaluate the attack performance on digital cases. For the physical evaluation, you can print the patch on a paper/iPad to reproduce Figure 5.

**Comment by ioo0s** [comment]
Thanks for the reply，i'll try to reproducing the AP results.
