### ISSUE TITLE
关于对抗效果的问题？

### ISSUE THREAD

**Issue by WateverOk** [VDIGPKU/T-SEA#14]
您好，我使用yolov5提供的官方代码调用摄像头进行了尝试，但是对抗样本的效果不是很好，请问有可能是什么原因造成的呢？补丁用的是您的仓库中的demo图片通过打印获得的，模型参数是yolov5s.pt
视频链接如下：
链接：https://pan.baidu.com/s/12oGVUkQVBZ_OvGhKg-ZTWQ 
提取码：empj 
--来自百度网盘超级会员V2的分享

**Comment by Juli-Eyre** [comment]
请问您解决了嘛

**Comment by ziyannchen** [comment]
您好，这个问题可以参考一下issue #11。我们在论文中使用的指标是AP，实际上反映的是这个patch攻击模型使其不能正常工作的程度，但是不能体现使所有检测框消失的比例（我相信您的疑问在这里）。如果想用后者，那么使用攻击成功率会更恰当，但那不是我们这篇工作的重点。您可以在后续的工作中继续讨论研究这个问题～
