### ISSUE TITLE
“ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2'”

### ISSUE THREAD

**Issue by WateverOk** [VDIGPKU/T-SEA#15]
“ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2'”
请问一下你们的pytorch和torchvision的版本是多少？我在运行ssd和faster rcnn时会报这个错！

**Comment by ziyannchen** [comment]
我们实验用的包的版本在[requirements.txt](https://github.com/VDIGPKU/T-SEA/blob/main/requirements.txt)里可以找到。
