### ISSUE TITLE
About gen_det_labels script can't save imgs

### ISSUE THREAD

**Issue by Kegard** [VDIGPKU/T-SEA#17]
In `gen_det_labels.py`, when I try to save imgs I run into this problems,  
`img_numpy, img_numpy_int8 = detector.unnormalize(img_tensor_batch[0])` In the detector, it hasn't the attribute ` unormalize`. And I don't find the `normalize` in the `dataloder`. I hope you can help me ! Thank you!!

**Comment by ziyannchen** [comment]
Thanks for reaching out and sorry for the late reply.
This is a bug. We reframed the whole pipeline before but kept this feature unmodified.
I've fixed it. Please check the latest update in the repo.
