### ISSUE TITLE
你好我在运行evaluate.py时出现cudaerror

### ISSUE THREAD

**Issue by YuanLinxi** [VDIGPKU/T-SEA#18]
我在运行evaluate.py执行您的readme
![8WXD9 %KROB%2QE082BS0EK](https://github.com/VDIGPKU/T-SEA/assets/136681516/b4c33dd5-eca7-43cb-b6b4-cc9e376cdd5a)
出现如下错误
![_XC7WY@UJF_%K2P4S3 ~$0G](https://github.com/VDIGPKU/T-SEA/assets/136681516/9fba4b14-79f9-4c42-85f4-5d52fb90b505)
我尝试更换cuda与torch版本，仍出现该问题，请问您遇到过类似的问题吗，或您知道如何解决该问题吗？

**Comment by Ysnnnn** [comment]
> 你好，这个应该是cuda和torch版本匹配的问题，和我们的代码仓库应该无关哈

请问您们用的CUDA版本是多少呀？我也遇到了这个问题。

**Comment by Ysnnnn** [comment]
> 我在运行evaluate.py执行您的readme ![8WXD9 %KROB%2QE082BS0EK](https://private-user-images.githubusercontent.com/136681516/287451100-b4c33dd5-eca7-43cb-b6b4-cc9e376cdd5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMDYzNDcsIm5iZiI6MTczNjMwNjA0NywicGF0aCI6Ii8xMzY2ODE1MTYvMjg3NDUxMTAwLWI0YzMzZGQ1LWVjYTctNDNjYi1iNmI0LWNjOWUzNzZjZGQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQwMzE0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjQ4ZGY4MTdkOWFiOGZiZjA4YzY3MzcyNjZmZWM0OWRlMWVhMTU5NTQ0NTU1YmJmZjNjOWNiMTNkNWVlNTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7q3RXD-7s9rGIhWiHjX7t1OB4HV-0cod3QYzgZXT_js) 出现如下错误 ![XC7WY@UJF%K2P4S3 ~$0G](https://private-user-images.githubusercontent.com/136681516/287451156-9fba4b14-79f9-4c42-85f4-5d52fb90b505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMDYzNDcsIm5iZiI6MTczNjMwNjA0NywicGF0aCI6Ii8xMzY2ODE1MTYvMjg3NDUxMTU2LTlmYmE0YjE0LTc5ZjktNGM0Mi04NWY0LTVkNTJmYjkwYjUwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQwMzE0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODQ4Yjg4YzRhMjA2MzdmNjJmOWQ5NTliZmU2ZTEzNjk1NGZkNjA0NDI1MjUxNzNlODhlZWU0YjI5YzkxZGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jDJvLXnqoUB8G9Gw-4UtFIBPd1aefMJo3K6BuSMqUec) 我尝试更换cuda与torch版本，仍出现该问题，请问您遇到过类似的问题吗，或您知道如何解决该问题吗？

请问您解决这个问题了吗？

**Comment by DarkLeaves** [comment]
> > 我在运行evaluate.py执行您的readme ![8WXD9 %KROB%2QE082BS0EK](https://private-user-images.githubusercontent.com/136681516/287451100-b4c33dd5-eca7-43cb-b6b4-cc9e376cdd5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMDYzNDcsIm5iZiI6MTczNjMwNjA0NywicGF0aCI6Ii8xMzY2ODE1MTYvMjg3NDUxMTAwLWI0YzMzZGQ1LWVjYTctNDNjYi1iNmI0LWNjOWUzNzZjZGQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQwMzE0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjQ4ZGY4MTdkOWFiOGZiZjA4YzY3MzcyNjZmZWM0OWRlMWVhMTU5NTQ0NTU1YmJmZjNjOWNiMTNkNWVlNTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7q3RXD-7s9rGIhWiHjX7t1OB4HV-0cod3QYzgZXT_js) 出现如下错误 ![XC7WY@UJF%K2P4S3 ~$0G](https://private-user-images.githubusercontent.com/136681516/287451156-9fba4b14-79f9-4c42-85f4-5d52fb90b505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMDYzNDcsIm5iZiI6MTczNjMwNjA0NywicGF0aCI6Ii8xMzY2ODE1MTYvMjg3NDUxMTU2LTlmYmE0YjE0LTc5ZjktNGM0Mi04NWY0LTVkNTJmYjkwYjUwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQwMzE0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODQ4Yjg4YzRhMjA2MzdmNjJmOWQ5NTliZmU2ZTEzNjk1NGZkNjA0NDI1MjUxNzNlODhlZWU0YjI5YzkxZGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jDJvLXnqoUB8G9Gw-4UtFIBPd1aefMJo3K6BuSMqUec) 我尝试更换cuda与torch版本，仍出现该问题，请问您遇到过类似的问题吗，或您知道如何解决该问题吗？
> 
> 请问您解决这个问题了吗？

应该是环境没配置好。我提供一个思路：新建一个py3.9的环境，然后首先安装pytorchyolo库，会自动安装低版本的torch三件套。然后卸载torch torchvision torchaudio，安装最新版的，基本就没问题了
