### ISSUE TITLE
您好 INRIAPerson标签缺失

### ISSUE THREAD

**Issue by comea23** [VDIGPKU/T-SEA#19]
您方便提供一下吗？谢谢

**Comment by ziyannchen** [comment]
请问指的是什么标签？README里面的云盘链接有放INRIAPerson测试集的标签

**Comment by ziyannchen** [comment]
> > 请问指的是什么标签？README里面的云盘链接有放INRIAPerson测试集的generated标签（我们用检测器检测出来的bbox）
> 
> 好像COCOPerson和INRIAPerson是同一个链接

已修正，感谢提醒！
