### ISSUE TITLE
请问每个测试数据集下的labels是怎么生成的，每个检测器对应labels都不一样，是按照数据集处理的方式处理的labels吗

### ISSUE THREAD

**Issue by ACoconut0313** [VDIGPKU/T-SEA#23]

**Comment by DarkLeaves** [comment]
测试集的label就是检测器自己生成的，所以不同的检测器的label都不一样。把检测器能检测到的目标当做gt。在这些能检测到的目标上贴patch，看看能否mislead检测器，这样来评估攻击效果。

**Comment by ziyannchen** [comment]
> 测试集的label就是检测器自己生成的，所以不同的检测器的label都不一样。把检测器能检测到的目标当做gt。在这些能检测到的目标上贴patch，看看能否mislead检测器，这样来评估攻击效果。

感谢回复～
文章中用到的就是这位朋友提到的相对AP。代码中相对和绝对验证两种方式都提供了，可以根据代码中的注释找到。
