### ISSUE TITLE
关于patch的尺寸问题

### ISSUE THREAD

**Issue by dwjwjy** [VDIGPKU/T-SEA#24]
您好，我发现在训练patch的时候，在demo.yaml文件中，patch的scale大小为0.15，但是在evaluate的时候，coco80.yaml文件中patch的scale为0.2，您在做实验的时候也是这样的设置吗？还是要把coco80.yaml的scale改成0.15？

**Comment by ziyannchen** [comment]
您好，首先训练时和测试时所用的patch scale可以分开讨论。

1、**training patch scale**（训练时所使用的scale称为training patch scale）：我们在论文里有具体说明training patch scale的setting，还在Fig 4讨论了不一样的training patch scale的区别。在E-Baseline中我们采用了scale=0.15，因为我们发现这种设置可以帮助学习更simple/global的pattern。
[config/demo.yaml](https://github.com/VDIGPKU/T-SEA/tree/main/configs/demo.yaml)是一个训练的配置样例，里面包含了论文Self-Ensemble Strategies所提的三种方法。

2、**testing patch scale**：论文中的digital attack实验测试所用的patch scale，因为需要和过去的工作对比，所以统一采用0.2。
[config/eval](https://github.com/VDIGPKU/T-SEA/tree/main/configs/eval)下的配置文件就是我们测试所用的setting。

**Comment by dwjwjy** [comment]
> Add a comment

非常感谢作者对我之前问题的解答！
还有个问题想请教一下您，在您提供的干净样本的label (yolov2-rescale-labels、.......、faster-rcnn-rescale-labels)中，您在生成这些label的时候有对图片进行pad_scale处理吗？因为我跑了一下gen_det_labels.py，生成出来的标签和您提供的有些差别，然后我看好像是因为您提供的标签没有进行pad_scale，直接对图片resize之后进行检测的；我按照您提供的gen_det_labels.py生成标签的时候是进行了pad_scale的。还有就是您提供的patch，在训练过程中，load图片的时候有进行pad_scale吗？如果生成标签的时候没有进行pad_scale处理，那么是不是在训练patch的过程中也不应该进行pad_scale处理呢。
