### ISSUE TITLE
缺失CCTVperson数据集ground-truth-rescale-labels 标签数据

### ISSUE THREAD

**Issue by zhongguadepi** [VDIGPKU/T-SEA#25]
您好，网盘提供的CCTVperson数据集label 中缺失了ground-truth-rescale-labels 标签数据。麻烦重新提供下数据集，万分感谢

**Comment by ziyannchen** [comment]
你好，CCTVperson这个数据集我们在论文标注了源数据集下载链接，这个数据集没有提供bbox标注，只有“w/”和“w/o” human object的分类，所以没有检测框GT哈。
