### ISSUE TITLE
About pretrained patch

### ISSUE THREAD

**Issue by Bomingmiao** [VDIGPKU/T-SEA#26]
Hi, your code is really wonderful. Could you please offer your pretrained AdvPatch on these models ? I would really appreciate it if you kept that and provide me with them.

**Comment by ziyannchen** [comment]
The pretrained AvdPatch has already offered in GoogleDrive / BaiduCloud, please refer to the patch zoo in the README file

**Comment by Bomingmiao** [comment]
> The pretrained AvdPatch has already offered in GoogleDrive / BaiduCloud, please refer to the patch zoo in the README file

Yes, I have downloaded the files from both GoogleDrive and BaiduCloud. You have offered all of the patches of T-SEA. But as for AdvPatch, which is the baseline and the competitive method in your paper, there is only one patch trained on YOLO v2. If you kept patches trained on the other models with the method of AdvPatch, can you share them with me?

**Comment by ziyannchen** [comment]
Hey, AdvPatch is provided by [the original paper](https://openaccess.thecvf.com/content_CVPRW_2019/papers/CV-COPS/Thys_Fooling_Automated_Surveillance_Cameras_Adversarial_Patches_to_Attack_Person_Detection_CVPRW_2019_paper.pdf) which you can find in [their ropo](https://gitlab.com/EAVISE/adversarial-yolo).
Note that we use the patch named [object_score.png](https://gitlab.com/EAVISE/adversarial-yolo/-/blob/master/patches/object_score.png?ref_type=heads) whose training objective is consistent with ours.
