### ISSUE TITLE
INRIAPerson训练集

### ISSUE THREAD

**Issue by shudong-zhang** [VDIGPKU/T-SEA#3]
INRIAPerson的数据集网上下不到，Google drive上只有test的，可以把完整训练集分享一下吗？

**Comment by Huaxingweichen** [comment]
Hi, we prepare a dataset download link: https://disk.pku.edu.cn:443/link/76B17498D1CC5DA092D9484E2DA0489A. Please note that this dataset is only for scientific research! If anyone think that we can not provide the data, please feel free to contact me.

您好，我们提供了下载链接: https://disk.pku.edu.cn:443/link/76B17498D1CC5DA092D9484E2DA0489A。请注意该数据仅供学术研究，如果任何人觉得我们不应该提供该数据集，请随时与我们联系。

**Comment by celinechanny** [comment]
You may also find the dataset on the official FTP server: ftp://ftp.inrialpes.fr/pub/lear/douze/data/INRIAPerson.tar
