### ISSUE TITLE
No ground-truth files found! 问题

### ISSUE THREAD

**Issue by zhongguadepi** [VDIGPKU/T-SEA#5]
运行测试文件 报错显示文件没有此文件
ground truth path        : /home/work/Users/Jetball/MainCode/attack/T-SEA-main/data/test/v5-demo/yolov5/det-labels
Error: No ground-truth files found!

**Comment by zycXD** [comment]
我们的评测代码提供了三种不同的GT-targets参考对的mAP计算方式，这里显示的路径末尾`det-labels`指的是在干净样本上的。
如果遇到这个报错可以尝试以下的解决方式：
1. 检查`v5-demo`文件夹下的报错对象文件夹det-labels中是否存在正常的检测标签`.txt`文件（`v5-demo/yolov5/det-labels`是我们预先在干净样本上使用yolov5检测器检测目标并保存目标信息的`.txt`文件，评测时会通过软链接方式链接到目标文件夹`v5-demo/yolov5`中，所以需要检查文件是否存在、链接是否正确）；
2. 如果1已经解决，尝试删除整个生成的测试文件夹`v5-demo`，然后重新运行`evaluate.py`；

关于1中所提到的预先检测的目标检测信息`.txt`文件，我们在论文中涉及到的模型检测文件都已经在主页提供，需要的话可以直接下载。如果使用仓库尚未支持的模型，需要在干净数据集上自行生成，可以参考[检测标签生成代码脚本](https://github.com/VDIGPKU/T-SEA/blob/main/utils/preprocesser/gen_det_labels.py)。

**Comment by zhongguadepi** [comment]
意思是先用yolov5 的detect.py 文件生成 *.txt文件复制到 det-labels文件下？

**Comment by zycXD** [comment]
`evaluate.py`这个脚本会自动进行软链接哈。如果是用我们仓库已经支持的模型（包括YoloV5），我们已经提供了在干净样本上检测的结果，直接下载即可。在测试时，运行`evaluate.py`这个脚本，只需要把这些结果文件夹的父文件夹的路径作为`-lp`参数传入即可。
```shell
├── labels
│   ├── ground-truth-rescale-labels
│   ├── faster_rcnn-rescale-labels
│   ├── ssd-rescale-labels
│   ├── yolov3-rescale-labels
│   ├── yolov3-tiny-rescale-labels
│   ├── yolov4-rescale-labels
│   ├── yolov4-tiny-rescale-labels
│   └── yolov5-rescale-labels
```
我们提供的检测文件的文件树如上，`-lp`参数提供上述`labels`的**绝对路径**即可。
如果上述操作都没问题，可以尝试删除结果文件夹重试哈。

**Comment by zycXD** [comment]
如果问题已经解决了的话，我先把issue关了哈，有什么问题欢迎继续提问。

**Comment by binyisu** [comment]
Hi, can you provide centernet-rescale-labels

**Comment by binyisu** [comment]
I have used you code to generate centernet-rescale-labels, thanks!

**Comment by zhongguadepi** [comment]
可以加我v15260332812




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "soda ***@***.***&gt;; 
发送时间: 2023年9月3日(星期天) 晚上11:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [VDIGPKU/T-SEA] No ground-truth files found! 问题 (Issue #5)





 
Hi, can you provide centernet-rescale-labels
