### ISSUE TITLE
保存的图像为空，测试的map=0

### ISSUE THREAD

**Issue by binyisu** [VDIGPKU/T-SEA#8]
/home/subinyi/anaconda3/envs/pytorch/bin/python /home/subinyi/Users/T-SEA-main/evaluate.py
Model init /home/subinyi/Users/T-SEA-main/detlib/HHDet/yolov5/yolov5/models/yolov5s.yaml
                     model cfg : HHDet/yolov5/yolov5/models/yolov5s.yaml
Reading patch from file: ./results/v5-demo.png
-------------------------Evaluating-------------------------
                         patch : ./results/v5-demo.png         
                           cfg : ./configs/eval/coco80.yaml    
                          save : /home/subinyi/Users/T-SEA-main/data/test/v5-demo
                    label_path : /home/subinyi/Users/T-SEA-main/data/INRIAPerson/Test/labels
                     data_root : /home/subinyi/Users/T-SEA-main/data/INRIAPerson/Test/pos
                   test_origin : False                         
                       test_gt : False                         
          stimulate_uint8_loss : False                         
                     save_imgs : /home/subinyi/Users/T-SEA-main/data/test/
                  gen_no_label : False                         
                     eva_class : 0                             
                         quiet : False                         
                eva_class_list : ['person']                    
                  ignore_class : ['cow', 'dog', 'skis', 'clock', 'tvmonitor', 'sportsball', 'spoon', 'horse', 'truck', 'oven', 'elephant', 'banana', 'broccoli', 'chair', 'bicycle', 'orange', 'bus', 'umbrella', 'firehydrant', 'refrigerator', 'toaster', 'fork', 'wineglass', 'vase', 'frisbee', 'donut', 'baseballglove', 'zebra', 'scissors', 'bench', 'knife', 'book', 'baseballbat', 'handbag', 'boat', 'cat', 'skateboard', 'suitcase', 'laptop', 'pizza', 'hotdog', 'bed', 'keyboard', 'parkingmeter', 'aeroplane', 'train', 'cup', 'cake', 'trafficlight', 'backpack', 'hairdrier', 'surfboard', 'stopsign', 'diningtable', 'sink', 'toilet', 'bowl', 'motorbike', 'snowboard', 'remote', 'mouse', 'sofa', 'sandwich', 'tennisracket', 'car', 'pottedplant', 'kite', 'cellphone', 'tie', 'giraffe', 'carrot', 'bear', 'bird', 'bottle', 'microwave', 'apple', 'teddybear', 'toothbrush', 'sheep']
100%|██████████| 288/288 [01:58<00:00,  2.44it/s]
ln -s  /home/subinyi/Users/T-SEA-main/data/INRIAPerson/Test/labels/yolov5-rescale-labels /home/subinyi/Users/T-SEA-main/data/test/v5-demo/yolov5/det-labels
ground truth path        : /home/subinyi/Users/T-SEA-main/data/test/v5-demo/yolov5/det-labels
0.00% = person AP 
mAP = 0.00%
n classes:  1
No class-related preprocesser to be plotted!
n classes:  1
n classes:  1
ln -s  /home/subinyi/Users/T-SEA-main/data/INRIAPerson/Test/labels/ground-truth-rescale-labels /home/subinyi/Users/T-SEA-main/data/test/v5-demo/yolov5/ground-truth
        Attack Performance. AP : {'yolov5': 0.0}               
           See results in path : /home/subinyi/Users/T-SEA-main/data/test/v5-demo

Process finished with exit code 0

下图为保存的图像：
![crop001501](https://github.com/VDIGPKU/T-SEA/assets/35132544/0295c11d-ce5a-4b7f-b230-a223c65ed867)

**Comment by zycXD** [comment]
哈喽，
之前还没有出现过类似的bug。
如果输入的命令没有问题的话，请检查一下README中需要准备的文件是否都已经准备好，并且检查对应的数据文件是否正常。

**Comment by binyisu** [comment]
/home/subinyi/anaconda3/envs/pytorch/bin/python /home/subinyi/Users/T-SEA-main/train_optim.py
True
Model init /home/subinyi/Users/T-SEA-main/detlib/HHDet/yolov5/yolov5/models/yolov5s-shakedrop.yaml
                     model cfg : HHDet/yolov5/yolov5/models/yolov5s-shakedrop.yaml
--------------------------Training--------------------------
                           cfg : ./configs/demo.yaml           
                          time : Wed May 24 23:43:04 2023      
----------------------------DATA----------------------------
               CLASS_NAME_FILE : configs/namefiles/coco80.names
                       AUGMENT : 1                             
                       IMG_DIR : data/INRIAPerson/Train/pos    
                       LAB_DIR : None                          
--------------------------DETECTOR--------------------------
                          NAME : ['YOLOV5']                    
                    INPUT_SIZE : [416, 416]                    
                    BATCH_SIZE : 8                             
                   CONF_THRESH : 0.5                           
                    IOU_THRESH : 0.45                          
                          GATE : shakedrop                     
--------------------------ATTACKER--------------------------
                        METHOD : optim                         
                       EPSILON : 255                           
                     MAX_EPOCH : 100                           
                     ITER_STEP : 1                             
                       STEP_LR : 0.03                          
                  ATTACK_CLASS : 0                             
                     LOSS_FUNC : obj-tv                        
                        tv_eta : 2.5                           
                  LR_SCHEDULER : ALRS                          
                         WIDTH : 300                           
                        HEIGHT : 300                           
                         SCALE : 0.15                          
                          INIT : gray                          
                     TRANSFORM : ['jitter', 'rotate', 'median_pool', 'cutout']
----------------------------END-----------------------------
Gray initializing a universal patch
Epoch 1:   0%|          | 0/77 [00:00<?, ?it/s]Cutout level:  instance ; cutout ratio:  0.4 ; random shift:  -0.05
Epoch 1:   0%|          | 0/77 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/subinyi/Users/T-SEA-main/train_optim.py", line 111, in <module>
    train_uap(cfg, detector_attacker, save_patch_name, args)
  File "/home/subinyi/Users/T-SEA-main/train_optim.py", line 66, in train_uap
    loss = detector_attacker.attack(img_tensor_batch, mode='optim')
  File "/home/subinyi/Users/T-SEA-main/attack/attacker.py", line 167, in attack
    loss = self.attacker.non_targeted_attack(img_tensor_batch, detector)
  File "/home/subinyi/Users/T-SEA-main/attack/methods/base.py", line 81, in non_targeted_attack
    loss.backward()
  File "/home/subinyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/subinyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
  File "/home/subinyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/function.py", line 87, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore[attr-defined]
  File "/home/subinyi/Users/T-SEA-main/detlib/HHDet/yolov5/yolov5/models/shakedrop/shake_drop.py", line 44, in backward
    return beta * grad_output, None, None, None
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Process finished with exit code 1

**Comment by binyisu** [comment]
![crop001573](https://github.com/VDIGPKU/T-SEA/assets/35132544/a0ecf649-0ad9-49e1-90e4-5df306036527)
使用训练生成的patch的攻击效果差是什么原因？
/home/subinyi/anaconda3/envs/pytorch/bin/python /home/subinyi/Users/T-SEA-main/evaluate.py
Model init /home/subinyi/Users/T-SEA-main/detlib/HHDet/yolov5/yolov5/models/yolov5s.yaml
                     model cfg : HHDet/yolov5/yolov5/models/yolov5s.yaml
Reading patch from file: ./results/v5-demo.png
-------------------------Evaluating-------------------------
                         patch : ./results/v5-demo.png         
                           cfg : ./configs/eval/coco80.yaml    
                          save : /home/subinyi/Users/T-SEA-main/data/test/v5-demo
                    label_path : /home/subinyi/Users/T-SEA-main/data/INRIAPerson/Test/labels
                     data_root : /home/subinyi/Users/T-SEA-main/data/INRIAPerson/Test/pos
                   test_origin : False                         
                       test_gt : False                         
          stimulate_uint8_loss : False                         
                     save_imgs : /home/subinyi/Users/T-SEA-main/data/test/
                  gen_no_label : False                         
                     eva_class : 0                             
                         quiet : False                         
                eva_class_list : ['person']                    
                  ignore_class : ['teddybear', 'aeroplane', 'bed', 'spoon', 'oven', 'fork', 'bear', 'bench', 'bird', 'keyboard', 'laptop', 'horse', 'firehydrant', 'boat', 'dog', 'carrot', 'hairdrier', 'sink', 'backpack', 'bus', 'refrigerator', 'cow', 'bottle', 'snowboard', 'zebra', 'tvmonitor', 'baseballglove', 'sheep', 'train', 'wineglass', 'cellphone', 'clock', 'pottedplant', 'hotdog', 'sandwich', 'baseballbat', 'cake', 'tie', 'tennisracket', 'kite', 'microwave', 'toothbrush', 'scissors', 'bowl', 'remote', 'giraffe', 'skateboard', 'donut', 'handbag', 'frisbee', 'sofa', 'sportsball', 'vase', 'knife', 'truck', 'parkingmeter', 'bicycle', 'skis', 'broccoli', 'book', 'elephant', 'suitcase', 'toilet', 'banana', 'stopsign', 'cat', 'chair', 'apple', 'car', 'surfboard', 'trafficlight', 'umbrella', 'cup', 'motorbike', 'orange', 'pizza', 'toaster', 'mouse', 'diningtable']
100%|██████████| 288/288 [00:08<00:00, 35.14it/s]
ln -s  /home/subinyi/Users/T-SEA-main/data/INRIAPerson/Test/labels/yolov5-rescale-labels /home/subinyi/Users/T-SEA-main/data/test/v5-demo/yolov5/det-labels
ground truth path        : /home/subinyi/Users/T-SEA-main/data/test/v5-demo/yolov5/det-labels
3.83% = person AP 
mAP = 3.83%
n classes:  1
n classes:  1
n classes:  1
ln -s  /home/subinyi/Users/T-SEA-main/data/INRIAPerson/Test/labels/ground-truth-rescale-labels /home/subinyi/Users/T-SEA-main/data/test/v5-demo/yolov5/ground-truth
        Attack Performance. AP : {'yolov5': 3.83}              
           See results in path : /home/subinyi/Users/T-SEA-main/data/test/v5-demo

Process finished with exit code 0

**Comment by binyisu** [comment]
还有一个问题是，如果我想选mimpatch更新方法参数里面如何设置呢？
DATA:
  CLASS_NAME_FILE: 'configs/namefiles/coco80.names'
  AUGMENT: 1

  TRAIN:
    IMG_DIR: 'data/INRIAPerson/Train/pos'
    LAB_DIR:

DETECTOR:
  NAME: ["YOLOV5"]
  INPUT_SIZE: [416, 416]
  BATCH_SIZE: 8
  CONF_THRESH: 0.5
  IOU_THRESH: 0.45

  PERTURB:
    GATE: 'shakedrop'

ATTACKER:
  METHOD: "mim"
#  METHOD: "optim"
  EPSILON: 255
  MAX_EPOCH: 1000
  ITER_STEP: 1
  STEP_LR: 0.03
  ATTACK_CLASS: '0'
  LOSS_FUNC: "obj-tv"
  tv_eta: 2.5
  LR_SCHEDULER: 'ALRS'

  PATCH:
    WIDTH: 300
    HEIGHT: 300
    SCALE: 0.15
    INIT: "gray"
    TRANSFORM: ['jitter', 'rotate', 'median_pool', 'cutout']
#    TRANSFORM: ['rotate', 'median_pool']

**Comment by binyisu** [comment]
您好，我尝试加入一个新的损失，但是总是报如下错误，希望您能够帮我解决一下这个问题，万分感谢！
Gray initializing a universal patch
Epoch 1:   0%|          | 0/39 [00:00<?, ?it/s]Cutout level:  instance ; cutout ratio:  0.4 ; random shift:  -0.05
Epoch 1:   0%|          | 0/39 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/subinyi/Users/T-SEA-main/train_optim.py", line 111, in <module>
    train_uap(cfg, detector_attacker, save_patch_name, args)
  File "/home/subinyi/Users/T-SEA-main/train_optim.py", line 66, in train_uap
    loss = detector_attacker.attack(img_tensor_batch, mode='optim')
  File "/home/subinyi/Users/T-SEA-main/attack/attacker.py", line 167, in attack
    loss = self.attacker.non_targeted_attack(img_tensor_batch, detector)
  File "/home/subinyi/Users/T-SEA-main/attack/methods/base.py", line 86, in non_targeted_attack
    wh_loss1.backward()
  File "/home/subinyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/subinyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [81, 1]], which is output 0 of SliceBackward, is at version 2; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Process finished with exit code 1

我的损失如下：
            if hasattr(self.cfg, 'class_specify'):
                # TODO: only support filtering a single cls now
                attack_cls = int(self.cfg.ATTACK_CLASS)
                confs = torch.cat(
                    ([conf[cls == attack_cls].max(dim=-1, keepdim=True)[0] for conf, cls in zip(confs, cls_array)]))
            elif hasattr(self.cfg, 'topx_conf'):
                # attack top x confidence
                # print(confs.size())
                confs = torch.sort(confs, dim=-1, descending=True)[0][:, :self.cfg.topx_conf]
                confs = torch.mean(confs, dim=-1)

            else:
                # only attack the max confidence
                confs = confs.max(dim=-1, keepdim=True)[0]

            # 损失
            wh_loss = []
            for i, pred in enumerate(bboxes):
                x1 = pred[:, [0]]
                x2 = pred[:, [2]]
                w_span = torch.abs(x1 - x2)
                wh_loss.append(torch.mean(w_span))
            wh_loss1 = torch.mean(torch.stack(wh_loss, dim=0))
            wh_loss1.backward()
