### ISSUE TITLE
attack-labels File not found 问题

### ISSUE THREAD

**Issue by DUANYULI** [VDIGPKU/T-SEA#9]
您好，我在尝试运行eval.sh和evaluate.py，但是出现了如下报错，我检查了attack-labels，这好像是一个运行时生成的文件夹，里面什么也没有，请问这个是什么问题，如何解决呢，谢谢？

0it [00:01, ?it/s]
ln -s  /content/drive/MyDrive/proj/T-SEA/data/INRIAPerson/Test/labels/yolov2-rescale-labels /content/drive/MyDrive/proj/T-SEA/eval/inria/demo/v5-demo/yolov2/det-labels
ground truth path        : /content/drive/MyDrive/proj/T-SEA/eval/inria/demo/v5-demo/yolov2/det-labels
Error. File not found: /content/drive/MyDrive/proj/T-SEA/eval/inria/demo/v5-demo/yolov2/attack-labels/crop001501.txt
(You can avoid this error message by running extra/intersect-gt-and-dr.py)

**Comment by zycXD** [comment]
你好，attck-labels确实是运行时产生的文件夹，是把目标patch贴到样本上后再进行模型推理得到的检测结果。
出现这个错误可能是标签文件和数据文件名称存在不匹配的原因（例如数据中没有crop001501，但是ground truth出现了这个标签）。
检查一下配置文件里的data和label的路径是否正确，另外对应的文件夹里的数据是否正确。

**Comment by DUANYULI** [comment]
谢谢，已解决。祝你牛逼！

**Comment by qbyoutui** [comment]
你好，请问你是怎么解决的呢？我遇到了和你一样的问题。

**Comment by DUANYULI** [comment]
你好，我当时的解决方法是将Image和label这两个文件放在同一目录下。
